version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./dockerfile
      args:
        VITE_BACKEND_URL: "http://localhost:8000"
        VITE_BASE_URL: "http://localhost:8000"
    ports:
      - 3000:3000
    environment:
      - VITE_BASE_URL=quantinfinium.azurewebsites.net


 